### ISSUE TITLE
Production JS includes source mappings

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/react-injector#5]
The built version of this module includes source mappings which makes the file size quite large. Might be worth disabling source maps for production builds to keep the module a bit leaner.

**Comment by ScopeyNZ** [comment]
Provided the source maps are separate files it should be fine - the browser won't download them unless you open the developer tools. Note that there's an issue for doing this with all SS modules:

https://github.com/silverstripe/silverstripe-framework/issues/9127

**Comment by ScopeyNZ** [comment]
I'll leave this open though because they're not a separate file 😅

**Comment by elliot-sawyer** [comment]
This prevents the SilverStripe MFA tool from running when a strict content security policy is in place. `unsafe-eval` is needed run the module, which should never be necessary, but it's unavoidable here because the source maps include `eval()` statements. These should be removed from the production build

Context: https://github.com/silverstripe/silverstripe-mfa/issues/358

**Comment by ScopeyNZ** [comment]
@Cheddam I don't think the source maps have actually been removed from the build have they? Did you mean to close this?

**Comment by Cheddam** [comment]
@ScopeyNZ The source map is now in a [separate file](https://github.com/silverstripe/react-injector/blob/master/dist/injector.js.map), so I think that covers this issue 👍
